### ISSUE TITLE
IDs

### ISSUE THREAD

**Issue by aphelionz** [ptoner/orbit-db-join-store#1]
Continuing our conversation from [Gitter](https://gitter.im/orbitdb/Lobby), I'm thinking it might be better to temporarily change the ID of the _other_ log, instead of your own. That way you should be able to get the entries, the indexing, AND the order all in one go.

**Comment by ptoner** [comment]
Ok cool. What would be different about that? I don't really understand the implications.

**Comment by aphelionz** [comment]
That way all the final entries in the join store would all have the same log id, the id of the join store.

**Comment by ptoner** [comment]
Oh! Gotcha. That makes sense.

**Comment by ptoner** [comment]
Hmm. Seeing weird behavior.

When I change it to:

```javascript
    for (let store of this._stores) {

        //Temporarily change store's id to match the JoinStore's ID
        const tmpID = store._oplog.id

        store._oplog._id = this._oplog.id

        await this._oplog.join(store._oplog)

        //Change the ID back
        store._oplog._id = tmpID
    }
```

I only end up having the last one from each store. Aka "C", "F", and "I"

**Comment by aphelionz** [comment]
hmm ok, that's too bad. I'll keep thinking of different approaches
